tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "python"
brew "asciinema"
brew "bash"
brew "bat"
brew "binutils"
brew "bison"
brew "certbot"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "libssh2"
brew "diffutils"
brew "ed"
brew "editorconfig"
brew "fdupes"
brew "findutils"
brew "fish"
brew "fswatch"
brew "fzf"
brew "gawk"
brew "gcc"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "git"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "npth"
brew "gnupg"
brew "harfbuzz"
brew "gnuplot"
brew "go"
brew "grep"
brew "gtkglext"
brew "gzip"
brew "handbrake"
brew "httpd", restart_service: true
brew "httpie"
brew "hub"
brew "imagemagick"
brew "node"
brew "insect"
brew "jq"
brew "less"
brew "lftp"
brew "libarchive"
brew "lsyncd"
brew "lv"
brew "mackup"
brew "mas"
brew "maven"
brew "mono"
brew "moreutils"
brew "mysql", restart_service: true
brew "nano"
brew "neofetch"
brew "neovim"
brew "nkf"
brew "nmap"
brew "oath-toolkit"
brew "open-babel"
brew "pandoc"
brew "perl-build"
brew "php", restart_service: true
brew "pinentry-mac"
brew "povray"
brew "rename"
brew "rsync"
brew "ruby"
brew "ruby-build"
brew "rust"
brew "screen"
brew "shellcheck"
brew "sift"
brew "sl"
brew "socat"
brew "source-highlight"
brew "speedtest-cli"
brew "the_silver_searcher"
brew "tig"
brew "tika"
brew "tmux"
brew "tree"
brew "ttfautohint"
brew "vim"
brew "volt"
brew "watch"
brew "wdiff"
brew "wget"
brew "wine"
brew "winetricks"
brew "xmlstarlet"
brew "yamllint"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zenity"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alacritty"
cask "appcleaner"
cask "aquaterm"
cask "atok"
cask "avogadro"
cask "bitbar"
cask "coteditor"
cask "daisydisk"
cask "discord"
cask "dropbox"
cask "duet"
cask "filezilla"
cask "font-fantasque-sans-mono"
cask "font-fira-code"
cask "font-hasklig"
cask "font-iosevka"
cask "font-monoid"
cask "font-noto-color-emoji"
cask "font-noto-emoji"
cask "font-noto-mono"
cask "font-noto-sans"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif"
cask "font-noto-serif-cjk-jp"
cask "font-rubik"
cask "font-sarasa-gothic"
cask "font-source-han-code-jp"
cask "github"
cask "gitup"
cask "google-backup-and-sync"
cask "google-chrome"
cask "handbrake"
cask "hyper"
cask "inkdrop"
cask "java"
cask "karabiner-elements"
cask "keka"
cask "kitematic"
cask "launchbar"
cask "macdown"
cask "makemkv"
cask "mendeley"
cask "metaz"
cask "moom"
cask "ngrok"
cask "omnifocus"
cask "onedrive"
cask "popclip"
cask "powershell"
cask "readcube"
cask "skype"
cask "skype-for-business"
cask "skypewebplugin"
cask "slack"
cask "the-unarchiver"
cask "time-lapse-assembler"
cask "typora"
cask "unlox"
cask "vlc"
cask "whatsapp"
cask "xquartz"
mas "AirBrowser", id: 948620309
mas "Airmail", id: 918858936
mas "Amphetamine", id: 937984704
mas "Battery Monitor", id: 836505650
mas "Dark Mode for Safari", id: 1397180934
mas "Disk Diag", id: 672206759
mas "Display Menu", id: 549083868
mas "Dropshelf", id: 540404405
mas "Folder Sync", id: 433026186
mas "Gapplin", id: 768053424
mas "GIFQuickMaker", id: 411431426
mas "GIPHY CAPTURE", id: 668208984
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Memory Diag", id: 748212890
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Reeder", id: 880001334
mas "Snappy", id: 512617038
mas "Xcode", id: 497799835
